services:
  webase:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "vue_data:/usr/share/nginx/html"
    restart: always # unless-stopped

  webvue:
    build: 
      context: .
      dockerfile: extra/Dockerfile-vue
    ports:
      - "8008:8080"
    restart: no

  srvuser:
    build:
      context: .
      dockerfile: extra/Dockerfile-user
    ports:
      - "3000:8080"
    restart: on-failure:1 # Tipo valor máximo status code: 5

volumes:
  vue_data:
