version: "3.9"

services:
  database:
    image: mysql:5.7.33
    volumes:
      - "database_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:5.6.1
    depends_on:
      - database
    volumes:
      - "wordpress_data:/var/www/html"
    restart: always
    ports:
      - "8008:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

volumes:
  database_data:
  wordpress_data:
