FROM tomcat:8.5-alpine

LABEL autor="xNibble" \
    contact="info@xnibble.com" \
    version="v0.0.1" \
    description="Image with several sentences for Dockerfile"

RUN <<EOT
    addgroup -S app
    adduser -S student -G app
EOT

USER student